version: '3.3'

services:

  openldap:
    image: docker.io/bitnami/openldap:2
    environment:
      - LDAP_ADMIN_USERNAME=${ADMIN_USERNAME?Variable not set}
      - LDAP_ADMIN_PASSWORD=${ADMIN_PASSWORD?Variable not set}
      - LDAP_USERS=${USER_NAMES?Variable not set}
      - LDAP_PASSWORDS=${USER_PASSWORDS?Variable not set}
    networks:
      - openldap-network
    volumes:
      - openldap-data:/bitnami/openldap
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-network
        - traefik.constraint-label=traefik-proxy
        - traefik.http.routers.openldap-http.rule=Host(`openldap.${DOMAIN?Variable not set}`)
        - traefik.http.routers.openldap-http.entrypoints=http
        - traefik.http.routers.openldap-http.middlewares=https-redirect
        - traefik.http.routers.openldap-https.rule=Host(`openldap.${DOMAIN?Variable not set}`)
        - traefik.http.routers.openldap-https.entrypoints=https
        - traefik.http.routers.openldap-https.tls=true
        - traefik.http.routers.openldap-https.tls.certresolver=le
        - traefik.http.services.openldap.loadbalancer.server.port=1636

networks:
  openldap-network:
    attachable: true

volumes:
  openldap-data:
