version: '3.3'

services:

  atlassian-jira:
    image: atlassian/jira-software:latest
    volumes:
      - jira-data:/var/atlassian/application-data/jira
    environment:
      - X_PROXY_NAME=jira.${DOMAIN?Variable not set}
      - X_PROXY_PORT=443
      - X_PROXY_SCHEME=https
    networks:
      - jira-network
      - traefik-network
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.platform.os == linux
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-network
        - traefik.constraint-label=traefik-proxy
        - traefik.http.routers.jira-http.rule=Host(`jira.${DOMAIN?Variable not set}`)
        - traefik.http.routers.jira-http.entrypoints=http
        - traefik.http.routers.jira-http.middlewares=https-redirect
        - traefik.http.routers.jira-https.rule=Host(`jira.${DOMAIN?Variable not set}`)
        - traefik.http.routers.jira-https.entrypoints=https
        - traefik.http.routers.jira-https.tls=true
        - traefik.http.routers.jira-https.tls.certresolver=le
        - traefik.http.services.jira.loadbalancer.server.port=8080

networks:
  jira-network:
    attachable: true
  traefik-network:
    external: true

volumes:
  jira-data:
