version: '3.3'

services:

  docker-dind:
    image: docker.io/docker:dind
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - docker-certs-ca:/certs/ca:rw,delegated
      - docker-certs-client:/certs/client:rw,delegated
    networks:
      - docker-network
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.platform.os == linux

  agent:
    image: docker.io/gocd/gocd-agent-docker-dind:v22.2.0
    environment:
      - GO_SERVER_URL=${GO_SERVER_URL?Variable not set}
      - AGENT_AUTO_REGISTER_KEY=${AGENT_AUTO_REGISTER_KEY?Variable not set}
      - AGENT_AUTO_REGISTER_ENVIRONMENTS=${AGENT_AUTO_REGISTER_ENVIRONMENTS?Variable not set}
      - AGENT_AUTO_REGISTER_RESOURCES=${AGENT_AUTO_REGISTER_RESOURCES?Variable not set}
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs:ro
    volumes:
      - docker-certs-client:/certs
    networks:
      - docker-network
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.platform.os == linux

networks:
  docker-network:
    attachable: true

volumes:
  docker-certs-ca:
  docker-certs-client:
