version: '3.3'

services:

  agent:
    image: docker.io/gocd/gocd-agent-docker-dind:v22.2.0
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - GO_SERVER_URL=${GO_SERVER_URL?Variable not set}
      - AGENT_AUTO_REGISTER_KEY=${AGENT_AUTO_REGISTER_KEY?Variable not set}
      - AGENT_AUTO_REGISTER_ENVIRONMENTS=${AGENT_AUTO_REGISTER_ENVIRONMENTS?Variable not set}
      - AGENT_AUTO_REGISTER_RESOURCES=${AGENT_AUTO_REGISTER_RESOURCES?Variable not set}
    volumes:
      - docker-data:/certs
    networks:
      - docker-network
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.platform.os == linux

  docker-dind:
    image: docker.io/docker:dind
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-data:/certs
    networks:
      - docker-network
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.platform.os == linux

networks:
  docker-network:
    attachable: true

volumes:
  docker-data: