version: '3.3'

services:

  agent:
    image: docker.io/gocd/gocd-agent-docker-dind:v22.2.0
    environment:
      - GO_SERVER_URL=${GO_SERVER_URL?Variable not set}
      - AGENT_AUTO_REGISTER_KEY=${AGENT_AUTO_REGISTER_KEY?Variable not set}
      - AGENT_AUTO_REGISTER_ENVIRONMENTS=${AGENT_AUTO_REGISTER_ENVIRONMENTS?Variable not set}
      - AGENT_AUTO_REGISTER_RESOURCES=${AGENT_AUTO_REGISTER_RESOURCES?Variable not set}
      - DOCKER_TLS_VERIFY=1
      - DOCKER_HOST=${DOCKER_HOST?Variable not set}
      - DOCKER_CERT_PATH=/certs
    volumes:
      - docker-certs-data-01:/certs:ro
    networks:
      - docker-network
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.platform.os == linux

networks:
  docker-network:
    attachable: true

volumes:
  docker-certs-data-01:
    external: true