version: '3.3'

services:

  portainer:
    image: docker.io/portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    networks:
      - portainer-network
      - traefik-network
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-network
        - traefik.constraint-label=traefik-proxy
        - traefik.http.routers.portainer-http.rule=Host(`portainer.${DOMAIN?Variable not set}`)
        - traefik.http.routers.portainer-http.entrypoints=http
        - traefik.http.routers.portainer-http.middlewares=https-redirect
        - traefik.http.routers.portainer-https.rule=Host(`portainer.${DOMAIN?Variable not set}`)
        - traefik.http.routers.portainer-https.entrypoints=https
        - traefik.http.routers.portainer-https.tls=true
        - traefik.http.routers.portainer-https.tls.certresolver=le
        - traefik.http.services.portainer.loadbalancer.server.port=9000

  agent:
    image: docker.io/portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
    networks:
      - portainer-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

networks:
  portainer-network:
    attachable: true
  traefik-network:
    external: true

volumes:
  portainer-data: